### ISSUE TITLE
3D Druck Files

### ISSUE THREAD

**Issue by gruselhaus** [Jugendhackt/parteiduell-joystick#1]
@Max20013108 Kannst du bitte die 3D Files in das Repo hier reinpacken, welche du schon hast?

**Comment by gruselhaus** [comment]
@Max20013108 Wie sieht's aus? Ich habe heute einen 3D Drucker am Start.

**Comment by Smaxs2001** [comment]
Hab ich eben habe aber vor die noch zu verbessern. Kann das ja auch selber ausdrucken drucker läuft wieder.

**Comment by gruselhaus** [comment]
Ok, top 👍🏻
